{
	"version": 1535147534,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/gg_title_spr-sheet0.png",
		"images/gg_title_spr-sheet1.png",
		"images/gg_title_spr-sheet2.png",
		"images/gg_title_spr-sheet3.png",
		"images/gg_title_spr-sheet4.png",
		"images/gg_title_spr-sheet5.png",
		"images/gg_title_spr-sheet6.png",
		"images/gg_title_spr-sheet7.png",
		"images/gg_title_spr-sheet8.png",
		"images/gg_title_spr-sheet9.png",
		"images/gg_title_spr-sheet10.png",
		"images/gg_title_spr-sheet11.png",
		"images/title-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite4-sheet1.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sugar-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite8-sheet1.png",
		"images/sprite8-sheet2.png",
		"images/sprite8-sheet3.png",
		"images/sprite8-sheet4.png",
		"images/sprite8-sheet5.png",
		"images/sprite8-sheet6.png",
		"images/sprite8-sheet7.png",
		"images/sprite8-sheet8.png",
		"images/sprite8-sheet9.png",
		"images/sprite8-sheet10.png",
		"images/sprite8-sheet11.png",
		"images/sprite8-sheet12.png",
		"images/sprite8-sheet13.png",
		"images/sprite8-sheet14.png",
		"images/sprite8-sheet15.png",
		"images/sprite8-sheet16.png",
		"images/sprite8-sheet17.png",
		"images/sprite8-sheet18.png",
		"images/sprite8-sheet19.png",
		"images/sprite8-sheet20.png",
		"images/sprite8-sheet21.png",
		"images/sprite8-sheet22.png",
		"images/sprite8-sheet23.png",
		"images/sprite8-sheet24.png",
		"images/sprite8-sheet25.png",
		"images/sprite8-sheet26.png",
		"media/gg_title.ogg",
		"media/give powder.m4a",
		"media/give powder.ogg",
		"media/i'm gg.m4a",
		"media/i'm gg.ogg",
		"media/thats the stuff.m4a",
		"media/thats the stuff.ogg",
		"media/sugar.m4a",
		"media/sugar.ogg",
		"media/add some more.m4a",
		"media/add some more.ogg",
		"media/finish it.m4a",
		"media/finish it.ogg",
		"media/oh yeah.m4a",
		"media/oh yeah.ogg",
		"media/see you soon.m4a",
		"media/see you soon.ogg",
		"media/bumpbump.m4a",
		"media/bumpbump.ogg",
		"media/gg_title.m4a",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"gg_title.mp4",
		"gg_0000_sugar1.png",
		"gg_0001_sugar2.png",
		"gg_0002_sugar3.png",
		"gg_0004_layer-9.png",
		"gg_0005_layer-10.png",
		"gg_0006_ggbase.png",
		"gg_0007_splash1.png",
		"gg_0008_splash2.png",
		"gg_0009_ggfull.png",
		"gg_0010_gghalf.png",
		"gg_0011_layer-3.png",
		"gg_0012_layer-2.png",
		"gg_0013_jug1.png",
		"gg_0014_juglid.png",
		"gg_0015_jugnolid.png"
	]
}